<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>
<?php if(isset($_POST['name'])){ echo $_POST['name'] .' - Provisional Marks Card Generated by SSIT360';}
	else { echo 'CGPA Calucalater Tool Server SSIT360';}?>
</title>
<style type="text/css">
.container { width:300px; margin:0  auto;}
.container input {width: 100%;clear: both;}

.res_container {width:600px; margin:0  auto;}
.res_container h2 {width: 100%;text-align:left;font-size:18px;}


table{font: 11px/24px Verdana, Arial, Helvetica, sans-serif;border-collapse: collapse;width: 600px;}
th {padding: 0 0.5em;text-align: left;}
tr.yellow th {border-top: 1px solid #FB7A31;border-bottom: 1px solid #FB7A31;background: #FFC;}

td {border-bottom: 1px solid #CCC;padding: 0 0.5em;}
td.subject {border-bottom: 1px solid #CCC;padding: 0 0.5em; text-align:left;}

td+td {border-left: 1px solid #CCC;text-align: center;}

h1,h3 { text-align:center;}
h2{ margin-left:20px;text-align:right;}
footer { text-align:center;color:#ccc;font-size:12px;}
p{font-size:12px;text-align:left;}

tr.one td{font-size:12px; text-align: left; width:auto;}
tr.one td+td {border-left: 0px solid #000;text-align: left;}

.entry_container { width:600px; margin:0  auto;}
.entry_container input { width: 100%;clear: both; }
    </style>
</head>

<body>
<h1>Sri Siddhartha Institute of Technology, Tumkur</h1>
<h3> (A Constituent College of Sri Siddhartha Academy of Higher Education)</h3>

	<?php error_reporting(0);
	
	//Subject Enter Form
	if(!isset($_POST['no_of_subjects']) AND !isset($_POST['credit']))
	{
		echo '	<div  class="container">
				<form action="'. $_SERVER["PHP_SELF"] .'" method="POST">
				<fieldset>
				<legend>Enter Details</legend>
				
				
				Number of Subjects:<input type="text" name="no_of_subjects" ><br/><br/>
				
    			<input type="submit" value="Submit" />
				</fieldset>
				</form>
				</div><footer> &copy;2013 SSIT360. Integrating Innovations. </footer>';

	}//Endif
	
	// Grade, Credit Form
	if(isset($_POST['no_of_subjects']))
	{	
		$no_of_sub = $_POST['no_of_subjects'];
		echo '	<div class="entry_container">
				<form action="'. $_SERVER["PHP_SELF"] .'" method="POST" id="cgpa_form">
					<fieldset>
  						<legend>Enter Details</legend>
						 Name:<input type="text" name="name" autofocus><br/>
				Father Name:<input type="text" name="father_name" ><br/>
				USN:<input type="text" name="usn" ><br/>
				
				Branch - Course:<input list="courses"  name="course" >
				<!-- HTML5  Datalist Tag -->
				<datalist id="courses">
  								<option  value=" B E - Computer Science and Engineering">
								<option value=" B E - Electrical and Electronics Engineering ">
								<option  value=" B E - Electronics And Communication Engineering ">
								<option value=" B E - Industrial Engineering and Management">
								<option  value=" B E - Information Science And Engineering ">
								<option  value=" MCA - Master of Computer Applications ">
								<option  value=" B E - Mechanical Engineering ">
								<option  value=" B E - Medical Electronics and Engineering ">
								<option  value=" M Tech - Computer Science and Engineering">
								<option  value=" M Tech - ">
				</datalist><br/>
				Semister:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<select name="semester">
								<option  value="1">I</option>
								<option value="2">II</option>
								<option  value="3">III</option>
								<option value="4">IV</option>
								<option  value="5">V</option>
								<option  value="6">VI</option>
								<option  value="7">VII</option>
								<option  value="8">VII</option>
								</select>
								<br/><br/>
				Year/Month of Exam:<input type="text" name="exam_date" ><br/>
						<table border="1">
							<tr>
								<th width="10">Serial</th>
        						<th width="40">Subject Code</th>
								<th >Subject Name</th>
        						<th width="40">Credits</th>
								<th width="40">Grade</th>
        						
							</tr>';
	
							for ($i = 0; $i < $no_of_sub; $i++) 
							{
    						echo ' 
							
							<tr>
									<td> '.  ( $i + 1 ).'</td>
									<td> <input type="text" name="subject_code[]"></td>
									<td> <input type="text" name="subject_name[]"></td>
    								<td><input type="text" name="credit[]" /></td>
       								 <td> <select name="grade[]" form="cgpa_form"> 
            								<option value="10">S</option>
                							<option value="9">A</option>
               								<option value="8">B</option>
                							<option value="7">C</option>
											<option value="5">D</option>  
											<option value="4">E</option>  
											<option value="0">F</option>  
											
        									</select>
        							</td>
       
    							</tr>';
  							}//Endfor
  					echo '</table>
						<input type="reset" value="Reset" onclick="foucs(name);" /><br/> <hr>
							<input type="submit" value="Submit" />
					</fieldset>
				</form>
			</div><footer> &copy;2013 SSIT360. Integrating Innovations. </footer>';
		}//Endif Grade, Credit Form
	
	
	//Report 
	if(isset($_POST['credit']))
	{	
		
		
		//POSTing Credits from Form
		$credits = $_POST['credit'];
		//POSTting Grades from Form
		$points = $_POST['grade'];
		$subject_code = $_POST['subject_code'];
		$subject_name = $_POST['subject_name'];
		//Variable Declaration
		$total = 0;
		$i = 0;
		$result = 0;
		$total_points =0;
		$sgpa = 0;
		$total_credits =0;
		//Report Generation
		echo '
				<h1>EXTRACT OF RESULT</h1>
				<div class="res_container">
				<table >
				<tr class="one"><td >Name</td><td>:<i>&nbsp;'.strtoupper($_POST['name']).'</i> </td></tr> 
				<tr class="one"><td> Father Name</td><td>:<i>&nbsp;'.strtoupper($_POST['father_name']).'</i> </td></tr>
				<tr class="one"><td> USN</td><td>:<i>&nbsp;'.strtoupper($_POST['usn']).'</i> </td></tr>
				<tr class="one"><td> Course</td><td>:<i>&nbsp;'.strtoupper($_POST['course']).'</i>&nbsp;&nbsp; </td></tr>
				<tr class="one"><td> Semester</td><td>:&nbsp;<i>'.$_POST['semester'].'</i> </td></tr>
				<tr class="one"><td> &nbsp;Month/Year of Exam</td><td>:&nbsp;<i>'.strtoupper($_POST['exam_date']).'</i> </td></tr></table>';
				
		
		
	
	echo '<br/>';
	//Printing Table
	echo '<table border="1"  align="center">
			<tr class="yellow" > 
			<th>Serial</th>
			<th> Subject Code</th>
			<th> Subject Title</th>
			<th> Credit </th>
			<th> Grade Awarded </th>  
			<th> Grade Points </th>  
			</tr>    ';
	
	for( $i = 0; $i < count($credits) ; $i++ )
		{ 	$total_credits = $total_credits + $credits[$i];
		
			$total_points = $total_points + ( $points[$i] * $credits[$i] ) ;
			$result +=  $points[$i];
			
			echo '<tr>
			<td scope="row" align="center" width="10">'. ($i + 1) .' </td>
			<td width="30">'. strtoupper($subject_code[$i]).' </td>
			<td class="subject" align="left">'. strtoupper($subject_name[$i]).' </td>
			<td width="10">'.  $credits[$i].' </td>
			<td  width="10">'. ( $points[$i] == 10 ? 'S' : ( $points[$i] == 9 ? 'A' : ( $points[$i] == 8 ? 'B' : ( $points[$i] == 7 ? 'C' : ( $points[$i] == 5 ? 'D' : ( $points[$i] == 4 ? 'E' : ( $points[$i] == 0 ? 'F' : 'Error' ) ) ))))).' </td>
			<td width="10">'. $points[$i].' </td>
			</tr>';
		}//Endfor
		//Calculating CGPA
		
		$sgpa =  $total_points / $total_credits  ;

	
		echo '<tr>
		<td colspan="6" align="center"> <strong>Total Credits:'.$total_credits.'&nbsp;|&nbsp;Semester Grade Point Average :</strong> '.sprintf('%01.2f', $sgpa).'</td>
		
		
		</tr> </table> ';
		echo '<p class="print-date">Date'. date(' d / M / Y h:i:s A').'</p>';
		echo '<br><br><p style="text-align:right;margin-right:50px;font-size:18px;"> Registrar (Eval)</p>';
		echo '</div>';
		echo '<center><input type="button" value="Print this page" onclick="window.print()"> </center> ';
		}//Endif Results
	//End PHP
	?>






</body>
</html>